services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile.open-webui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      SCARF_NO_ANALYTICS: "true"
      DO_NOT_TRACK: "true"
      ANONYMIZED_TELEMETRY: "false"
      RAG_EMBEDDING_ENGINE: ollama
      RAG_EMBEDDING_MODEL: nomic-embed-text
    volumes:
      - ./OpenWebUI/tools:/app/backend/data/tools:ro
      - ./SurzsEnviro:/workspace/SurzsEnviro:rw
      - ./dockerstuff:/workspace/dockerstuff
      - ./dockerstuff/OpenWebUI/data:/app/backend/data:rw

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      JUPYTER_AI_OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      SCARF_NO_ANALYTICS: "true"
      DO_NOT_TRACK: "true"
      ANONYMIZED_TELEMETRY: "false"
    volumes:
      - /home/surzal/git:/home/jovyan/work/git
      - ./dockerstuff:/home/jovyan/work/dockerstuff
    command: >
      bash -c "
        jupyter lab
      "
